###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "bananaka@gmail.com",
  "password": "bananaka"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
 "nama" : "bananaka",
 "email" : "bananaka@gmail.com",
 "password" : "bananaka",
 "umur" : "15",
 "sekolah" : "smp6padang",
 "jenis_kelamin" : "pria"
}

###
GET http://localhost:3000/lapor/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYW5hbmFrYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNTc5NDM4NX0.IiGn1Zhkk1zjBw1JFA1rlO9rQ4VJ0yoXuRtsCv9HQsw

###
POST http://localhost:3000/lapor
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYW5hbmFrYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNTc5NDM4NX0.IiGn1Zhkk1zjBw1JFA1rlO9rQ4VJ0yoXuRtsCv9HQsw
Content-Type: application/json

{
  "keterangan": "laporan kedua dikirim"
}

### 
DELETE http://localhost:3000/lapor/8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYW5hbmFrYUBnbWFpbC5jb20iLCJpYXQiOjE3MTU2NjM0NjZ9.PF5kpOiQedVoAmbRtfd2eyTYLHNjKh9BfLN52seqRn8

###
PATCH  http://localhost:3000/lapor/7/true
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYW5hbmFrYUBnbWFpbC5jb20iLCJpYXQiOjE3MTU2NjM0NjZ9.PF5kpOiQedVoAmbRtfd2eyTYLHNjKh9BfLN52seqRn8
Content-Type: application/json

###
POST http://localhost:3000/artikel
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYW5hbmFrYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNTc5NDY0M30._iZv9EFm1h-y1R_mCRiOU85KLwukuREqz49P34w3mY4
Content-Type: application/json

{
  "highlight_isi": "headline",
  "judul": "Judul",
  "isi": "Isi",
  "penulis": "penulis",
  "pekerjaan": "pekerjaan"
}

###
GET http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJiYW5hbmFrYUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNTg2OTA5OX0.q42WK0_yiqhhv6alX4MQdWUjuIRdNgQ30QyWL3Ct2uI
